/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoungExplorersRouteImport } from './routes/young-explorers'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as GroupProgrammeRouteImport } from './routes/group-programme'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardResourcesRouteImport } from './routes/dashboard/resources'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCompleteRouteImport } from './routes/auth/complete'
import { Route as DashboardResourcesResourceIdRouteImport } from './routes/dashboard/resources.$resourceId'
import { Route as DashboardCourseCourseIdVideosRouteImport } from './routes/dashboard/course.$courseId.videos'
import { Route as DashboardCourseCourseIdResourcesRouteImport } from './routes/dashboard/course.$courseId.resources'

const YoungExplorersRoute = YoungExplorersRouteImport.update({
  id: '/young-explorers',
  path: '/young-explorers',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupProgrammeRoute = GroupProgrammeRouteImport.update({
  id: '/group-programme',
  path: '/group-programme',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardResourcesRoute = DashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth/complete',
  path: '/auth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResourcesResourceIdRoute =
  DashboardResourcesResourceIdRouteImport.update({
    id: '/$resourceId',
    path: '/$resourceId',
    getParentRoute: () => DashboardResourcesRoute,
  } as any)
const DashboardCourseCourseIdVideosRoute =
  DashboardCourseCourseIdVideosRouteImport.update({
    id: '/course/$courseId/videos',
    path: '/course/$courseId/videos',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCourseCourseIdResourcesRoute =
  DashboardCourseCourseIdResourcesRouteImport.update({
    id: '/course/$courseId/resources',
    path: '/course/$courseId/resources',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/consult': typeof ConsultRoute
  '/group-programme': typeof GroupProgrammeRoute
  '/portal': typeof PortalRoute
  '/young-explorers': typeof YoungExplorersRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/resources': typeof DashboardResourcesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/resources/$resourceId': typeof DashboardResourcesResourceIdRoute
  '/dashboard/course/$courseId/resources': typeof DashboardCourseCourseIdResourcesRoute
  '/dashboard/course/$courseId/videos': typeof DashboardCourseCourseIdVideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consult': typeof ConsultRoute
  '/group-programme': typeof GroupProgrammeRoute
  '/portal': typeof PortalRoute
  '/young-explorers': typeof YoungExplorersRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/resources': typeof DashboardResourcesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/resources/$resourceId': typeof DashboardResourcesResourceIdRoute
  '/dashboard/course/$courseId/resources': typeof DashboardCourseCourseIdResourcesRoute
  '/dashboard/course/$courseId/videos': typeof DashboardCourseCourseIdVideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/consult': typeof ConsultRoute
  '/group-programme': typeof GroupProgrammeRoute
  '/portal': typeof PortalRoute
  '/young-explorers': typeof YoungExplorersRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/resources': typeof DashboardResourcesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/resources/$resourceId': typeof DashboardResourcesResourceIdRoute
  '/dashboard/course/$courseId/resources': typeof DashboardCourseCourseIdResourcesRoute
  '/dashboard/course/$courseId/videos': typeof DashboardCourseCourseIdVideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/about'
    | '/consult'
    | '/group-programme'
    | '/portal'
    | '/young-explorers'
    | '/auth/complete'
    | '/auth/login'
    | '/auth/sign-up'
    | '/dashboard/resources'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/resources/$resourceId'
    | '/dashboard/course/$courseId/resources'
    | '/dashboard/course/$courseId/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consult'
    | '/group-programme'
    | '/portal'
    | '/young-explorers'
    | '/auth/complete'
    | '/auth/login'
    | '/auth/sign-up'
    | '/dashboard/resources'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/dashboard/resources/$resourceId'
    | '/dashboard/course/$courseId/resources'
    | '/dashboard/course/$courseId/videos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/about'
    | '/consult'
    | '/group-programme'
    | '/portal'
    | '/young-explorers'
    | '/auth/complete'
    | '/auth/login'
    | '/auth/sign-up'
    | '/dashboard/resources'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/resources/$resourceId'
    | '/dashboard/course/$courseId/resources'
    | '/dashboard/course/$courseId/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ConsultRoute: typeof ConsultRoute
  GroupProgrammeRoute: typeof GroupProgrammeRoute
  PortalRoute: typeof PortalRoute
  YoungExplorersRoute: typeof YoungExplorersRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/young-explorers': {
      id: '/young-explorers'
      path: '/young-explorers'
      fullPath: '/young-explorers'
      preLoaderRoute: typeof YoungExplorersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-programme': {
      id: '/group-programme'
      path: '/group-programme'
      fullPath: '/group-programme'
      preLoaderRoute: typeof GroupProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/resources': {
      id: '/dashboard/resources'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof DashboardResourcesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete': {
      id: '/auth/complete'
      path: '/auth/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resources/$resourceId': {
      id: '/dashboard/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/dashboard/resources/$resourceId'
      preLoaderRoute: typeof DashboardResourcesResourceIdRouteImport
      parentRoute: typeof DashboardResourcesRoute
    }
    '/dashboard/course/$courseId/videos': {
      id: '/dashboard/course/$courseId/videos'
      path: '/course/$courseId/videos'
      fullPath: '/dashboard/course/$courseId/videos'
      preLoaderRoute: typeof DashboardCourseCourseIdVideosRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/course/$courseId/resources': {
      id: '/dashboard/course/$courseId/resources'
      path: '/course/$courseId/resources'
      fullPath: '/dashboard/course/$courseId/resources'
      preLoaderRoute: typeof DashboardCourseCourseIdResourcesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardResourcesRouteChildren {
  DashboardResourcesResourceIdRoute: typeof DashboardResourcesResourceIdRoute
}

const DashboardResourcesRouteChildren: DashboardResourcesRouteChildren = {
  DashboardResourcesResourceIdRoute: DashboardResourcesResourceIdRoute,
}

const DashboardResourcesRouteWithChildren =
  DashboardResourcesRoute._addFileChildren(DashboardResourcesRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardResourcesRoute: typeof DashboardResourcesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCourseCourseIdResourcesRoute: typeof DashboardCourseCourseIdResourcesRoute
  DashboardCourseCourseIdVideosRoute: typeof DashboardCourseCourseIdVideosRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardResourcesRoute: DashboardResourcesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCourseCourseIdResourcesRoute: DashboardCourseCourseIdResourcesRoute,
  DashboardCourseCourseIdVideosRoute: DashboardCourseCourseIdVideosRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ConsultRoute: ConsultRoute,
  GroupProgrammeRoute: GroupProgrammeRoute,
  PortalRoute: PortalRoute,
  YoungExplorersRoute: YoungExplorersRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
